import { NextResponse } from "next/server";
import { requireOperatorApi } from "@/lib/auth/guards";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import type { OcrWord } from "@/lib/ocr/types";
import { extractLeafletCandidates } from "@/lib/leaflet-review/extractor";

export const runtime = "nodejs";
export const maxDuration = 120;
const BUCKET="leaflet-intake";
const SOURCE_PATH="billa/billa-2026-08-19__a7a0e1fef9b45d3b.pdf";
async function loadPdfDocument(bytes:Uint8Array){const worker=await import("pdfjs-dist/legacy/build/pdf.worker.mjs");(globalThis as typeof globalThis&{pdfjsWorker?:unknown}).pdfjsWorker={WorkerMessageHandler:worker.WorkerMessageHandler};const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");return pdfjs.getDocument({data:bytes.slice()}).promise;}
async function pageWords(doc:any,pageNo:number):Promise<OcrWord[]>{const page=await doc.getPage(pageNo);const content=await page.getTextContent();const words:OcrWord[]=[];for(const raw of content.items){if(!("str" in raw)||typeof raw.str!=="string")continue;const text=raw.str.trim();if(!text)continue;const t=Array.isArray(raw.transform)?raw.transform:[1,0,0,1,0,0];words.push({text,x:Number(t[4]??0),y:Number(t[5]??0),w:Math.max(1,Number(raw.width??text.length*5)),h:Math.max(1,Number(raw.height??Math.abs(Number(t[3]??10))))});}return words;}
const eq=(a:unknown,b:number)=>Math.abs(Number(a)-b)<.001;
export async function GET(){const gate=await requireOperatorApi();if(!gate.ok)return gate.response;const s=getSupabaseAdmin();if(!s)return NextResponse.json({ok:false,error:"Supabase není nakonfigurovaný."},{status:503});let doc:any=null;try{const {data:source,error}=await s.storage.from(BUCKET).download(SOURCE_PATH);if(error||!source)throw new Error(error?.message||"BILLA PDF chybí.");doc=await loadPdfDocument(new Uint8Array(await source.arrayBuffer()));const words=await pageWords(doc,1);const rows=extractLeafletCandidates(words,{pageNo:1,validFrom:"2026-08-19",validTo:"2026-08-25"});const find=(price:number,rx:RegExp)=>rows.filter(r=>eq(r.price_sale,price)).find(r=>rx.test(String(r.source_text||"")));const check=(id:string,r:any,qty:number,unit:string)=>({id,value:r?{pack_qty:r.pack_qty,pack_unit:r.pack_unit,pack_unit_qty:r.pack_unit_qty,pack_text:r.pack_text}:null,ok:!!r&&eq(r.pack_qty,qty)&&String(r.pack_unit||"").toLowerCase()===unit});const checks=[check("milka_90g",find(24.9,/Milka|Čokoláda/i),90,"g"),check("rajcata_250g",find(39.9,/Rajčata/i),250,"g"),check("tvaroh_250g",find(18.9,/Tvaroh/i),250,"g"),check("ondrasovka_1_5l",find(10.9,/ONDRÁŠOVKA|Minerální voda/i),1.5,"l"),check("toaletni_papir_360m",find(99.9,/Toaletní|papír/i),360,"m")];const failures=checks.filter(c=>!c.ok).map(c=>c.id);return NextResponse.json({ok:true,point_5d:{pass:failures.length===0,checks,failures}});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}finally{if(doc)await doc.destroy();}}
