"use client";

import { useState } from "react";

type Snapshot={id:string;fetched_at:string;source_url:string;source_html_path:string|null;manifest_path:string|null;product:{name:string;description:string|null;brand:string|null;sku:string|null;gtin:string|null;category:string|null;price:number|null;price_currency:string|null;availability:string|null;image_source_url:string|null;image_storage_path:string|null}};

export function CatalogCollector(){
 const[url,setUrl]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[result,setResult]=useState<Snapshot|null>(null);
 async function collect(){setBusy(true);setError("");setResult(null);try{const response=await fetch("/api/catalog/collect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url})});const data=await response.json().catch(()=>null);if(!response.ok||!data?.ok)throw new Error(data?.error??`HTTP ${response.status}`);setResult(data.snapshot);}catch(cause){setError(cause instanceof Error?cause.message:"Sběr produktu selhal.");}finally{setBusy(false)}}
 return <section className="rounded-3xl border border-indigo-200 bg-white p-6 shadow-sm sm:p-8"><label className="text-sm font-bold text-slate-900">URL produktu nebo e-shopu</label><div className="mt-3 flex flex-col gap-3 sm:flex-row"><input type="url" value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&url&&!busy)void collect()}} placeholder="https://eshop.cz/produkt" className="min-w-0 flex-1 rounded-2xl border border-slate-300 px-4 py-3"/><button type="button" disabled={!url||busy} onClick={()=>void collect()} className="rounded-2xl bg-indigo-700 px-6 py-3 font-bold text-white disabled:opacity-50">{busy?"Klonuji a stahuji…":"Klonovat produkt"}</button></div>{error?<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>:null}{result?<div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50/50 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-emerald-700">Uloženo</p><h2 className="mt-1 text-xl font-bold text-slate-900">{result.product.name}</h2><p className="mt-1 text-sm text-slate-600">{result.product.brand??"bez značky"} · {result.product.price??"—"} {result.product.price_currency??""}</p></div><a href={result.source_url} target="_blank" rel="noreferrer" className="text-sm font-bold text-indigo-700">Zdroj ↗</a></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="font-semibold text-slate-500">HTML snapshot</dt><dd className="break-all">{result.source_html_path}</dd></div><div><dt className="font-semibold text-slate-500">Stažený obrázek</dt><dd className="break-all">{result.product.image_storage_path??"na stránce nebyl nalezen"}</dd></div><div><dt className="font-semibold text-slate-500">Manifest</dt><dd className="break-all">{result.manifest_path}</dd></div><div><dt className="font-semibold text-slate-500">SKU / GTIN</dt><dd>{result.product.sku??"—"} / {result.product.gtin??"—"}</dd></div></dl></div>:null}</section>
}
