import { NextResponse } from "next/server";
import { requireOperatorApi } from "@/lib/auth/guards";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import type { OcrWord } from "@/lib/ocr/types";
import { extractLeafletCandidates } from "@/lib/leaflet-review/extractor";
export const runtime="nodejs"; export const maxDuration=120;
const BUCKET="leaflet-intake", SOURCE_PATH="billa/billa-2026-08-19__a7a0e1fef9b45d3b.pdf";
async function loadPdfDocument(bytes:Uint8Array){const worker=await import("pdfjs-dist/legacy/build/pdf.worker.mjs");(globalThis as typeof globalThis&{pdfjsWorker?:unknown}).pdfjsWorker={WorkerMessageHandler:worker.WorkerMessageHandler};const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");return pdfjs.getDocument({data:bytes.slice()}).promise;}
async function pageWords(doc:any,pageNo:number):Promise<OcrWord[]>{const page=await doc.getPage(pageNo),content=await page.getTextContent(),words:OcrWord[]=[];for(const raw of content.items){if(!("str" in raw)||typeof raw.str!=="string")continue;const text=raw.str.trim();if(!text)continue;const t=Array.isArray(raw.transform)?raw.transform:[1,0,0,1,0,0];words.push({text,x:Number(t[4]??0),y:Number(t[5]??0),w:Math.max(1,Number(raw.width??text.length*5)),h:Math.max(1,Number(raw.height??Math.abs(Number(t[3]??10))))});}return words;}
const eq=(a:unknown,b:number)=>Math.abs(Number(a)-b)<.001;
export async function GET(){const gate=await requireOperatorApi();if(!gate.ok)return gate.response;const s=getSupabaseAdmin();if(!s)return NextResponse.json({ok:false},{status:503});let doc:any=null;try{const {data:source,error}=await s.storage.from(BUCKET).download(SOURCE_PATH);if(error||!source)throw new Error(error?.message||"PDF chybí");doc=await loadPdfDocument(new Uint8Array(await source.arrayBuffer()));const words=await pageWords(doc,1);const rows=extractLeafletCandidates(words,{pageNo:1,validFrom:"2026-08-19",validTo:"2026-08-25"});const milka=rows.find(r=>eq(r.price_sale,24.9)&&/Milka|Čokoláda/i.test(String(r.source_text||"")));const interesting=words.filter(w=>/koupi|39,90|od\s*2\s*ks|1\s*ks|24,90/i.test(w.text)).map(w=>({text:w.text,x:w.x,y:w.y,w:w.w,h:w.h}));return NextResponse.json({ok:true,milka:milka?{bbox:milka.source_bbox,source_text:milka.source_text,extraction_payload:milka.extraction_payload}:null,interesting});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}finally{if(doc)await doc.destroy();}}
