import { NextResponse } from "next/server";
import { requireOperatorApi } from "@/lib/auth/guards";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import type { OcrWord } from "@/lib/ocr/types";
import { extractLeafletCandidates } from "@/lib/leaflet-review/extractor";
export const runtime="nodejs"; export const maxDuration=120;
const BUCKET="leaflet-intake", SOURCE_PATH="billa/billa-2026-08-19__a7a0e1fef9b45d3b.pdf";
async function loadPdfDocument(bytes:Uint8Array){const worker=await import("pdfjs-dist/legacy/build/pdf.worker.mjs");(globalThis as typeof globalThis&{pdfjsWorker?:unknown}).pdfjsWorker={WorkerMessageHandler:worker.WorkerMessageHandler};const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");return pdfjs.getDocument({data:bytes.slice()}).promise;}
async function pageWords(doc:any,pageNo:number):Promise<OcrWord[]>{const page=await doc.getPage(pageNo),content=await page.getTextContent(),words:OcrWord[]=[];for(const raw of content.items){if(!("str" in raw)||typeof raw.str!=="string")continue;const text=raw.str.trim();if(!text)continue;const t=Array.isArray(raw.transform)?raw.transform:[1,0,0,1,0,0];words.push({text,x:Number(t[4]??0),y:Number(t[5]??0),w:Math.max(1,Number(raw.width??text.length*5)),h:Math.max(1,Number(raw.height??Math.abs(Number(t[3]??10))))});}return words;}
const eq=(a:unknown,b:number|null)=>b===null?a==null:Math.abs(Number(a)-b)<.001;
export async function GET(){const gate=await requireOperatorApi();if(!gate.ok)return gate.response;const s=getSupabaseAdmin();if(!s)return NextResponse.json({ok:false,error:"Supabase není nakonfigurovaný."},{status:503});let doc:any=null;try{const {data:source,error}=await s.storage.from(BUCKET).download(SOURCE_PATH);if(error||!source)throw new Error(error?.message||"BILLA PDF chybí.");doc=await loadPdfDocument(new Uint8Array(await source.arrayBuffer()));const page1=extractLeafletCandidates(await pageWords(doc,1),{pageNo:1,validFrom:"2026-08-19",validTo:"2026-08-25"});const page2=extractLeafletCandidates(await pageWords(doc,2),{pageNo:2,validFrom:"2026-08-19",validTo:"2026-08-25"});const find=(rows:any[],sale:number,rx:RegExp)=>rows.filter(r=>eq(r.price_sale,sale)).find(r=>rx.test(String(r.source_text||"")));const check=(id:string,r:any,sale:number,std:number|null,loy:number|null,without:number|null)=>({id,value:r?{price_sale:r.price_sale,price_standard:r.price_standard,price_loyalty:r.price_loyalty,price_without_loyalty:r.price_without_loyalty,source_text:r.source_text}:null,ok:!!r&&eq(r.price_sale,sale)&&eq(r.price_standard,std)&&eq(r.price_loyalty,loy)&&eq(r.price_without_loyalty,without)});const checks=[check("kure",find(page1,49.9,/\bKuře\b/i),49.9,89.9,null,null),check("jihoceske_maslo",find(page1,32.9,/Jihočeské\s+máslo/i),32.9,44.9,32.9,44.9),check("toffifee",find(page1,29.9,/Toffifee/i),29.9,54.9,29.9,54.9),check("tvaroh",find(page1,18.9,/Tvaroh/i),18.9,29.9,null,null),check("lucina",find(page2,42.9,/\bLučina\b/i),42.9,64.9,null,null)];const failures=checks.filter(c=>!c.ok).map(c=>c.id);return NextResponse.json({ok:true,extractor_version:page2[0]?.extractor_version??page1[0]?.extractor_version??null,point_5e:{pass:failures.length===0,checks,failures}});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}finally{if(doc)await doc.destroy();}}
