import { NextRequest, NextResponse } from "next/server";
import { requireOperatorApi } from "@/lib/auth/guards";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import { processLeafletPdf } from "@/lib/leaflet-review/processor";
export const runtime="nodejs"; export const maxDuration=240;
const BUCKET="leaflet-intake",SOURCE_PATH="billa/billa-2026-08-19__a7a0e1fef9b45d3b.pdf";
const eq=(a:unknown,b:number)=>Math.abs(Number(a)-b)<.001;
async function cleanup(s:any,leafletId:string|null,importId:string|null,path:string){if(leafletId){const{data:c}=await s.from("leaflet_item_candidates").select("id").eq("leaflet_id",leafletId);const ids=(c??[]).map((x:any)=>x.id).filter(Boolean);if(ids.length)await s.from("leaflet_item_review_audit").delete().in("candidate_id",ids);await s.from("leaflet_notification_outbox").delete().eq("leaflet_id",leafletId);await s.from("leaflet_item_candidates").delete().eq("leaflet_id",leafletId);await s.from("leaflet_page_processing").delete().eq("leaflet_id",leafletId);await s.from("leaflet_documents").delete().eq("id",leafletId);if(importId)await s.from("imports").delete().eq("id",importId);}await s.storage.from(BUCKET).remove([path]);}
function forwardHeaders(req:NextRequest){const h:Record<string,string>={"content-type":"application/json"};const cookie=req.headers.get("cookie"),auth=req.headers.get("authorization");if(cookie)h.cookie=cookie;if(auth)h.authorization=auth;return h;}
async function action(req:NextRequest,id:string){const resp=await fetch(new URL("/api/leaflet-review",req.url),{method:"POST",headers:forwardHeaders(req),body:JSON.stringify({id,action:"reread"}),cache:"no-store"});const body=await resp.json();if(!resp.ok||!body?.ok)throw new Error(`reread API ${resp.status}: ${body?.error||"unknown"}`);return body.item;}
export async function GET(req:NextRequest){const gate=await requireOperatorApi();if(!gate.ok)return gate.response;const s=getSupabaseAdmin();if(!s)return NextResponse.json({ok:false},{status:503});const path=`_tests/reread-semantics-19-08-2026-25-08-2026-${Date.now()}.pdf`;let leafletId:string|null=null,importId:string|null=null;try{const{data:source,error}=await s.storage.from(BUCKET).download(SOURCE_PATH);if(error||!source)throw new Error(error?.message||"PDF chybí");const bytes=new Uint8Array(await source.arrayBuffer());const{error:ue}=await s.storage.from(BUCKET).upload(path,bytes,{contentType:"application/pdf",upsert:true});if(ue)throw new Error(ue.message);await processLeafletPdf({supabase:s,bucket:BUCKET,path,retailer:"billa",sourceUrl:"test://reread-semantics/billa",page:1,force:true});const{data:doc,error:de}=await s.from("leaflet_documents").select("id,import_id").eq("storage_bucket",BUCKET).eq("storage_path",path).single();if(de||!doc?.id)throw new Error(de?.message||"Dokument nevznikl");leafletId=String(doc.id);importId=typeof doc.import_id==="string"?doc.import_id:null;const{data:rows,error:re}=await s.from("leaflet_item_candidates").select("*").eq("leaflet_id",leafletId).eq("page_no",1);if(re)throw new Error(re.message);const tvaroh=(rows??[]).find((x:any)=>eq(x.price_sale,18.9)&&/Tvaroh/i.test(String(x.product_name||"")));const milka=(rows??[]).find((x:any)=>eq(x.price_sale,24.9)&&/Milka/i.test(String(x.product_name||"")));if(!tvaroh?.id||!milka?.id)throw new Error("Testovací kandidáti chybí");await s.from("leaflet_item_candidates").update({source_text:"CORRUPTED SOURCE",product_name:null,status:"quarantine",confidence:.1}).eq("id",tvaroh.id);const fixed=await action(req,tvaroh.id);const milkaBefore={brand:milka.brand,minimum_quantity:milka.minimum_quantity,promo_condition:milka.promo_condition,product_name:milka.product_name,price_sale:milka.price_sale};const milkaAfter=await action(req,milka.id);const getResp=await fetch(new URL(`/api/leaflet-review?leaflet_id=${encodeURIComponent(leafletId)}&page=1`,req.url),{headers:forwardHeaders(req),cache:"no-store"});const getBody=await getResp.json();if(!getResp.ok||!getBody?.ok)throw new Error(`GET review ${getResp.status}: ${getBody?.error||"unknown"}`);const persisted=(getBody.items??[]).find((x:any)=>x.id===tvaroh.id);const points={
point_6c:{checks:[{id:"source_replaced",value:fixed?.source_text??null,ok:!!fixed?.source_text&&fixed.source_text!=="CORRUPTED SOURCE"}]},
point_6d:{checks:[{id:"interpretation_reran",value:{name:fixed?.product_name,extractor:fixed?.extractor_version},ok:/Tvaroh/i.test(String(fixed?.product_name||""))&&!!fixed?.extractor_version}]},
point_6e:{checks:[{id:"better_result_replaces_missing_name",value:fixed?.product_name??null,ok:/Tvaroh/i.test(String(fixed?.product_name||""))}]},
point_6f:{checks:[{id:"milka_brand_preserved",value:{before:milkaBefore.brand,after:milkaAfter?.brand},ok:milkaBefore.brand==="Milka"&&milkaAfter?.brand==="Milka"},{id:"milka_promo_preserved",value:{before:{qty:milkaBefore.minimum_quantity,condition:milkaBefore.promo_condition},after:{qty:milkaAfter?.minimum_quantity,condition:milkaAfter?.promo_condition}},ok:milkaBefore.minimum_quantity===2&&milkaAfter?.minimum_quantity===2&&/^OD\s+2\s+KS$/i.test(String(milkaAfter?.promo_condition||""))},{id:"milka_core_not_degraded",value:{before:{name:milkaBefore.product_name,price:milkaBefore.price_sale},after:{name:milkaAfter?.product_name,price:milkaAfter?.price_sale}},ok:milkaAfter?.product_name===milkaBefore.product_name&&eq(milkaAfter?.price_sale,Number(milkaBefore.price_sale))}]},
point_6g:{checks:[{id:"reload_matches_saved_result",value:persisted?{source:persisted.source_text,name:persisted.product_name,revision:persisted.revision}:null,ok:!!persisted&&persisted.source_text===fixed.source_text&&persisted.product_name===fixed.product_name&&persisted.revision===fixed.revision}]}
};for(const p of Object.values(points) as any[]){p.failures=p.checks.filter((c:any)=>!c.ok).map((c:any)=>c.id);p.pass=p.failures.length===0;}const allPass=Object.values(points).every((p:any)=>p.pass);return NextResponse.json({ok:allPass,...points});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}finally{try{await cleanup(s,leafletId,importId,path);}catch(error){console.error("test-reread-semantics cleanup failed",error);}}}
