import { NextResponse } from "next/server";
import { requireOperatorApi } from "@/lib/auth/guards";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import type { OcrWord } from "@/lib/ocr/types";
import { extractLeafletCandidates } from "@/lib/leaflet-review/extractor";
import { applyCandidateQuality } from "@/lib/leaflet-review/quality-resolver";
export const runtime="nodejs"; export const maxDuration=120;
const BUCKET="leaflet-intake", SOURCE_PATH="billa/billa-2026-08-19__a7a0e1fef9b45d3b.pdf";
async function loadPdfDocument(bytes:Uint8Array){const worker=await import("pdfjs-dist/legacy/build/pdf.worker.mjs");(globalThis as typeof globalThis&{pdfjsWorker?:unknown}).pdfjsWorker={WorkerMessageHandler:worker.WorkerMessageHandler};const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");return pdfjs.getDocument({data:bytes.slice()}).promise;}
async function pageWords(doc:any,pageNo:number):Promise<OcrWord[]>{const page=await doc.getPage(pageNo),content=await page.getTextContent(),words:OcrWord[]=[];for(const raw of content.items){if(!("str" in raw)||typeof raw.str!=="string")continue;const text=raw.str.trim();if(!text)continue;const t=Array.isArray(raw.transform)?raw.transform:[1,0,0,1,0,0];words.push({text,x:Number(t[4]??0),y:Number(t[5]??0),w:Math.max(1,Number(raw.width??text.length*5)),h:Math.max(1,Number(raw.height??Math.abs(Number(t[3]??10))))});}return words;}
const eq=(a:unknown,b:number)=>Math.abs(Number(a)-b)<.001;
export async function GET(){const gate=await requireOperatorApi();if(!gate.ok)return gate.response;const s=getSupabaseAdmin();if(!s)return NextResponse.json({ok:false},{status:503});let doc:any=null;try{const {data:source,error}=await s.storage.from(BUCKET).download(SOURCE_PATH);if(error||!source)throw new Error(error?.message||"PDF chybí");doc=await loadPdfDocument(new Uint8Array(await source.arrayBuffer()));const rows=extractLeafletCandidates(await pageWords(doc,1),{pageNo:1,validFrom:"2026-08-19",validTo:"2026-08-25"}).map(applyCandidateQuality);const eggs=rows.find(r=>eq(r.price_sale,84.9)&&/podestýlková/i.test(String(r.product_name||""))),kure=rows.find(r=>eq(r.price_sale,49.9)&&/^Kuře$/i.test(String(r.product_name||""))),paper=rows.find(r=>eq(r.price_sale,99.9)&&/Toaletní\s+papír/i.test(String(r.product_name||"")));const checks=[{id:"descriptor_quarantine",value:eggs?{name:eggs.product_name,status:eggs.status,confidence:eggs.confidence,reason:eggs.review_reason}:null,ok:!!eggs&&eggs.status==="quarantine"&&Number(eggs.confidence)<=.2&&/descriptor_without_product_noun/i.test(String(eggs.review_reason||""))},{id:"clear_kure_not_quarantine",value:kure?{status:kure.status,confidence:kure.confidence}:null,ok:!!kure&&kure.status==="unreviewed"&&Number(kure.confidence)>.2},{id:"clear_paper_not_quarantine",value:paper?{status:paper.status,confidence:paper.confidence}:null,ok:!!paper&&paper.status==="unreviewed"&&Number(paper.confidence)>.2}];const failures=checks.filter(c=>!c.ok).map(c=>c.id);return NextResponse.json({ok:failures.length===0,point_6a:{pass:failures.length===0,checks,failures}});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}finally{if(doc)await doc.destroy();}}
