import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { collectPublicCatalog, parseStructuredCatalog, parseSchwarzCatalog, catalogValidity, allowedCatalogDocument, boundedBytes, readCatalogSource, CATALOG_RETAILERS } from "../lib/leaflet-monitor/public-catalog.ts";
import { publishPublicCatalog } from "../lib/leaflet-monitor/publish-catalog.ts";
const fixture=(name:string)=>readFileSync(new URL(`../fixtures/public-catalog/${name}`,import.meta.url),"utf8");
const today="2026-10-07";
assert.equal(CATALOG_RETAILERS.length,9);
for(const id of ["albert","tesco","globus"] as const){
 const rows=parseStructuredCatalog(id,fixture(`${id}.html`),today);
 assert.equal(rows.length,id==="globus"?1:2);
 assert.ok(rows.every(x=>x.validFrom===today && x.validTo==="2026-10-13"));
 assert.ok(rows.every(x=>allowedCatalogDocument(id,x.sourceUrl)));
 if(id!=="globus")assert.equal(parseStructuredCatalog(id,fixture(`${id}.html`),"2026-10-14").length,0);
}
assert.equal(parseSchwarzCatalog("lidl",JSON.parse(fixture("lidl.json")),today).length,1);
assert.equal(parseSchwarzCatalog("lidl",JSON.parse(fixture("lidl.json")),"2026-10-08")[0]?.validFrom,"2026-10-08");
assert.equal(parseSchwarzCatalog("kaufland",JSON.parse(fixture("kaufland.json")),today).length,2);
assert.deepEqual(catalogValidity("7. 10. - 13. 10.","2026"),{validFrom:today,validTo:"2026-10-13"});
assert.equal(catalogValidity("31. 2. - 4. 3. 2026"),null);
assert.deepEqual(catalogValidity("28. 12. - 3. 1. 2027"),{validFrom:"2026-12-28",validTo:"2027-01-03"});
assert.equal(allowedCatalogDocument("penny","https://files.rewe.co.at/PennyIntLeaflet/CZ/07_10_2026_tl2/","viewer"),true);
assert.equal(allowedCatalogDocument("penny","https://files.rewe.co.at/other/","viewer"),false);
assert.equal(allowedCatalogDocument("tesco","https://evil.example/a.pdf"),false);
assert.equal(allowedCatalogDocument("tesco","https://user:password@digitalcontent.api.tesco.com/a.pdf"),false);
await assert.rejects(readCatalogSource("http://127.0.0.1/a"),/untrusted_source/);
await assert.rejects(readCatalogSource("https://www.albert.cz/a",async()=>new Response(null,{status:302,headers:{location:"http://127.0.0.1/"}})),/untrusted_source/);
await assert.rejects(boundedBytes(new Response(new Uint8Array(100)),20),/source_too_large/);
const billaPdf="https://view.publitas.com/64069/2700042/pdfs/test.pdf?response-content-disposition=attachment%3B+filename%2A%3DUTF-8%27%27BILLA.cz%2520-%2520Velk%25C3%25BD%2520let%25C3%25A1k%25207.%252010.%2520-%252013.%252010.%25202026.pdf";
const billa=await collectPublicCatalog("billa",{today,fetchImpl:async()=>new Response(`<a href="${billaPdf}">Stáhnout PDF</a>`)});
assert.equal(billa.status,"ready"); assert.equal(billa.leaflets[0]?.validFrom,today);
const penny=await collectPublicCatalog("penny",{today,fetchImpl:async()=>new Response('<div>7. 10. - 13. 10. <a href="https://files.rewe.co.at/PennyIntLeaflet/CZ/07_10_2026_tl2/">Prohlédnout</a></div>')});
assert.equal(penny.leaflets[0]?.kind,"viewer");
const teta=await collectPublicCatalog("teta",{today,fetchImpl:async()=>new Response('<div>Teta leták 8. 10. 2026 - 19. 10. 2026 <a href="https://letak.tetadrogerie.cz/teta-letak-21-2026/">Zobrazit leták</a></div>')});
assert.equal(teta.status,"no_current_leaflet");
const failed=await collectPublicCatalog("albert",{today,fetchImpl:async()=>new Response("unavailable",{status:503})});
assert.equal(failed.status,"error"); assert.equal(failed.leaflets.length,0);
let existing:Record<string,unknown>|null=null,downloads=0,uploads=0;
const written:Record<string,unknown>[]=[];
const client={from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:existing,error:null})})}),upsert:async(row:Record<string,unknown>)=>{written.push(row);existing={id:"id",storage_path:row.storage_path,cover_storage_path:row.cover_storage_path,page_count:row.page_count};return {error:null};},update:(row:Record<string,unknown>)=>({eq:async()=>{written.push(row);return {error:null};}})}),storage:{from:()=>({upload:async()=>{uploads++;return {error:null};}})}};
const renderCover=async()=>({jpeg:new Uint8Array([255,216,255,217]),pageCount:41});
const pdfFetch=async()=>{downloads++;return new Response("%PDF-1.7\nfixture");};
const first=await publishPublicCatalog(client as never,billa,pdfFetch,renderCover);
assert.equal(first.published,1);assert.equal(first.downloaded,1);
assert.equal(written[0].notification_status,"disabled");
assert.equal(written[0].page_count,41);
assert.match(String(written[0].cover_storage_path),/\.cover\.jpg$/);
const second=await publishPublicCatalog(client as never,billa,pdfFetch,renderCover);
assert.equal(second.published,1);assert.equal(second.downloaded,0);assert.equal(downloads,1);
assert.equal(Object.hasOwn(written[1],"processing_status"),false);
assert.ok(uploads>=3);
existing=null;
const rejected=await publishPublicCatalog(client as never,billa,async()=>new Response("not a PDF"));
assert.equal(rejected.published,0);assert.ok(rejected.errors.some(e=>e.includes("invalid_pdf_signature")));
existing=null;
let viewerArchive:Record<string,unknown>|null=null;
const viewerClient={...client,storage:{from:()=>({upload:async(path:string,body:unknown,options:{contentType:string})=>{
  assert.equal(options.contentType,"application/json");
  if(path.endsWith(".html")) viewerArchive=JSON.parse(String(body));
  return {error:null};
}})}};
const viewerResult=await publishPublicCatalog(viewerClient as never,penny,async()=>new Response("<html>official viewer</html>"));
assert.equal(viewerResult.downloaded,1);assert.equal(viewerResult.errors.length,0);
assert.equal(Object.hasOwn(written.at(-1)!,"page_count"),false);
assert.equal((viewerArchive as Record<string,unknown>|null)?.html,"<html>official viewer</html>");
console.log("public catalog: source fixtures, validity, boundary checks, publication and repeat-run checks passed");
