import assert from "node:assert/strict";
import {currentGlobusSource,relayGlobusPdf} from "../lib/leaflet-monitor/globus-delivery.ts";
const row={retailer_id:"globus",source_url:"https://gapi.globus.cz/OnlineAsset/3/asset?assetID=e06b9817-3ce1-49dc-9541-0455cb28b5f2",valid_from:"2026-10-07",valid_to:"2026-10-13"};
const source=currentGlobusSource(row,"2026-10-09")!;
assert.ok(source);
assert.equal(currentGlobusSource(row,"2026-10-14"),null);
assert.equal(currentGlobusSource({...row,source_url:"https://evil.example/a.pdf"},"2026-10-09"),null);
assert.equal(currentGlobusSource({...row,retailer_id:"billa"},"2026-10-09"),null);
assert.equal(currentGlobusSource({...row,valid_from:null},"2026-10-09"),null);
const pdf="%PDF-1.7\nexample\n%%EOF";
const response=await relayGlobusPdf(source,async()=>new Response(pdf));
assert.equal(response.status,200);
assert.equal(response.headers.get("content-type"),"application/pdf");
assert.equal(await response.text(),pdf);
const chunks=["%P","DF-1.7\n","%%EOF"];
const split=await relayGlobusPdf(source,async()=>new Response(new ReadableStream({pull(c){const chunk=chunks.shift();if(chunk)c.enqueue(new TextEncoder().encode(chunk));else c.close();}})));
assert.equal(await split.text(),"%PDF-1.7\n%%EOF");
await assert.rejects(relayGlobusPdf(source,async()=>new Response("blocked",{status:522})),/unavailable/);
await assert.rejects(relayGlobusPdf(source,async()=>new Response("<html>")),/invalid_pdf/);
await assert.rejects(relayGlobusPdf(source,async()=>new Response(pdf,{headers:{"content-length":String(76*1024*1024)}})),/unavailable/);
console.log("Globus delivery: current-source policy, complete PDF stream and upstream failures passed");
