import { NextRequest, NextResponse } from "next/server";
import { requireOperatorApi } from "@/lib/auth/guards";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import { processLeafletPdf } from "@/lib/leaflet-review/processor";
export const runtime="nodejs"; export const maxDuration=240;
const BUCKET="leaflet-intake",SOURCE_PATH="billa/billa-2026-08-19__a7a0e1fef9b45d3b.pdf";
const eq=(a:unknown,b:number)=>Math.abs(Number(a)-b)<.001;
function headers(req:NextRequest){const h:Record<string,string>={"content-type":"application/json"};const c=req.headers.get("cookie"),a=req.headers.get("authorization");if(c)h.cookie=c;if(a)h.authorization=a;return h;}
async function call(req:NextRequest,id:string,action:string,extra:any={}){const r=await fetch(new URL("/api/leaflet-review",req.url),{method:"POST",headers:headers(req),body:JSON.stringify({id,action,...extra}),cache:"no-store"});let b:any={};try{b=await r.json();}catch{}return{status:r.status,body:b};}
const point=(checks:any[])=>{const failures=checks.filter(c=>!c.ok).map(c=>c.id);return{pass:!failures.length,checks,failures};};
async function countForCandidate(s:any,id:string){const{data,error}=await s.from("offers_raw").select("id,notes").like("notes",`%leaflet_candidate:${id}%`);if(error)throw new Error(error.message);return data??[];}
async function cleanup(s:any,leafletId:string|null,importId:string|null,path:string){if(leafletId){const{data:c}=await s.from("leaflet_item_candidates").select("id,approved_offer_id").eq("leaflet_id",leafletId);const ids=(c??[]).map((x:any)=>x.id).filter(Boolean);for(const id of ids){const rows=await countForCandidate(s,String(id));if(rows.length)await s.from("offers_raw").delete().in("id",rows.map((x:any)=>x.id));}if(ids.length)await s.from("leaflet_item_review_audit").delete().in("candidate_id",ids);await s.from("leaflet_notification_outbox").delete().eq("leaflet_id",leafletId);await s.from("leaflet_item_candidates").delete().eq("leaflet_id",leafletId);await s.from("leaflet_page_processing").delete().eq("leaflet_id",leafletId);await s.from("leaflet_documents").delete().eq("id",leafletId);if(importId)await s.from("imports").delete().eq("id",importId);}await s.storage.from(BUCKET).remove([path]);}
export async function GET(req:NextRequest){const gate=await requireOperatorApi();if(!gate.ok)return gate.response;const s=getSupabaseAdmin();if(!s)return NextResponse.json({ok:false},{status:503});const path=`_tests/point10-19-08-2026-25-08-2026-${Date.now()}.pdf`;let leafletId:string|null=null,importId:string|null=null;try{const{data:source,error}=await s.storage.from(BUCKET).download(SOURCE_PATH);if(error||!source)throw new Error(error?.message||"PDF chybí");const bytes=new Uint8Array(await source.arrayBuffer());const{error:ue}=await s.storage.from(BUCKET).upload(path,bytes,{contentType:"application/pdf",upsert:true});if(ue)throw new Error(ue.message);await processLeafletPdf({supabase:s,bucket:BUCKET,path,retailer:"billa",sourceUrl:"test://point10",page:1,force:true});const{data:doc,error:de}=await s.from("leaflet_documents").select("id,import_id").eq("storage_path",path).single();if(de||!doc?.id)throw new Error(de?.message||"Dokument nevznikl");leafletId=String(doc.id);importId=doc.import_id?String(doc.import_id):null;const{data:rows,error:re}=await s.from("leaflet_item_candidates").select("*").eq("leaflet_id",leafletId).eq("page_no",1);if(re)throw new Error(re.message);const t=(rows??[]).find((x:any)=>eq(x.price_sale,18.9)&&/Tvaroh/i.test(String(x.source_text||"")));const k=(rows??[]).find((x:any)=>eq(x.price_sale,49.9)&&/^Kuře$/i.test(String(x.product_name||"")));const q=(rows??[]).find((x:any)=>eq(x.price_sale,84.9));const bad=(rows??[]).find((x:any)=>eq(x.price_sale,39.9)&&/Rajčata/i.test(String(x.source_text||"")));if(!t?.id||!k?.id||!q?.id||!bad?.id)throw new Error("Chybí testovací kandidáti");
// 10a: required fields block approval.
await call(req,bad.id,"edit",{changes:{product_name:null}});const invalidApprove=await call(req,bad.id,"approve");const invalidRows=await countForCandidate(s,bad.id);
// 10c/10d: rejected/quarantined never enter offers_raw.
await call(req,k.id,"reject",{note:"point10 reject"});await call(req,q.id,"quarantine",{note:"point10 quarantine"});const rejectedRows=await countForCandidate(s,k.id), quarantineRows=await countForCandidate(s,q.id);
// 10b/10e/10f/10g: edit known values, approve twice, inspect raw row(s).
const changes={product_name:"Tvaroh point10",brand:"POINT10",variant:"test",pack_qty:2,pack_unit:"g",pack_unit_qty:125,pack_text:"2×125 g",price_sale:17.9,price_standard:29.9,price_loyalty:16.9,price_without_loyalty:29.9,price_per_unit:7.16,price_per_unit_unit:"100 g",item_valid_from:"2026-08-20",item_valid_to:"2026-08-24",loyalty_required:true,promo_label:"TEST",promo_condition:"OD 2 KS",minimum_quantity:2};
const edit=await call(req,t.id,"edit",{changes});if(edit.status!==200)throw new Error(`edit failed ${edit.status}`);const first=await call(req,t.id,"approve");const afterFirst=await countForCandidate(s,t.id);const second=await call(req,t.id,"approve");const afterSecond=await countForCandidate(s,t.id);const rawId=String(first.body?.offer_id??"");const{data:raw,error:oe}=rawId?await s.from("offers_raw").select("*").eq("id",rawId).single():{data:null,error:null};if(oe)throw new Error(oe.message);const p10a=point([{id:"required_fields_block_invalid_approve",value:{status:invalidApprove.status,count:invalidRows.length},ok:invalidApprove.status===409&&invalidRows.length===0}]);const p10b=point([{id:"one_approve_one_row",value:{status:first.status,count:afterFirst.length},ok:first.status===200&&afterFirst.length===1}]);const p10c=point([{id:"reject_no_raw",value:rejectedRows.length,ok:rejectedRows.length===0}]);const p10d=point([{id:"quarantine_no_raw",value:quarantineRows.length,ok:quarantineRows.length===0}]);const p10e=point([{id:"double_approve_idempotent",value:{secondStatus:second.status,rows:afterSecond.map((x:any)=>x.id)},ok:second.status===200&&afterSecond.length===1}]);const p10f=point([{id:"all_source_fields_mapped",value:raw,ok:!!raw&&raw.extracted_name===changes.product_name&&raw.brand===changes.brand&&eq(raw.price_total,17.9)&&eq(raw.price_standard,29.9)&&eq(raw.price_with_loyalty_card,16.9)&&raw.has_loyalty_card_price===true&&eq(raw.typical_price_per_unit,7.16)&&Number(raw.pack_qty)===2&&raw.pack_unit==="g"&&Number(raw.pack_unit_qty)===125&&raw.valid_from==="2026-08-20"&&raw.valid_to==="2026-08-24"&&/OD 2 KS/.test(String(raw.notes||""))}]);const p10g=point([{id:"persisted_raw_source_values_not_overwritten",value:raw&&{name:raw.extracted_name,price:raw.price_total,standard:raw.price_standard,pack:[raw.pack_qty,raw.pack_unit_qty,raw.pack_unit]},ok:!!raw&&raw.extracted_name===changes.product_name&&eq(raw.price_total,17.9)&&eq(raw.price_standard,29.9)&&Number(raw.pack_qty)===2&&Number(raw.pack_unit_qty)===125&&raw.pack_unit==="g"}]);const result={point_10a:p10a,point_10b:p10b,point_10c:p10c,point_10d:p10d,point_10e:p10e,point_10f:p10f,point_10g:p10g};const pass=Object.values(result).every(x=>x.pass);return NextResponse.json({ok:pass,...result});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}finally{try{await cleanup(s,leafletId,importId,path);}catch(e){console.error("point10 cleanup",e);}}}
