import { createHash } from "node:crypto";
import type { OcrWord } from "@/lib/ocr/types";
import { extractLeafletCandidates } from "./extractor";
import { sendLeafletNotification } from "./notify";

const EXTRACTOR_MODEL = "local-pdf-text-layout-v3";
function pad(n:number){return String(n).padStart(2,"0")}
function iso(y:number,m:number,d:number){return `${y}-${pad(m)}-${pad(d)}`}
function decoded(value:string|null|undefined){if(!value)return"";try{return decodeURIComponent(value.replace(/\+/g," "))}catch{return value}}
function parseValidity(text:string,path:string,sourceUrl:string|null):{from:string|null;to:string|null;source:string|null}{
  const all=`${decoded(sourceUrl)} ${decoded(path)} ${text}`;
  const six=all.match(/(\d{1,2})[.\-_ ]+(\d{1,2})[.\-_ ]+(\d{4})\s*[-–—_]\s*(\d{1,2})[.\-_ ]+(\d{1,2})[.\-_ ]+(\d{4})/);
  if(six)return{from:iso(Number(six[3]),Number(six[2]),Number(six[1])),to:iso(Number(six[6]),Number(six[5]),Number(six[4])),source:six[0]};
  const explicit=all.match(/(?:nabídka\s+platí[^\d]{0,50})?od(?:\s+[A-Za-zÁ-ž]+)?\s+(\d{1,2})\.\s*(\d{1,2})\.?\s+do(?:\s+[A-Za-zÁ-ž]+)?\s+(\d{1,2})\.\s*(\d{1,2})\.?\s*(\d{4})/i);
  if(explicit)return{from:iso(Number(explicit[5]),Number(explicit[2]),Number(explicit[1])),to:iso(Number(explicit[5]),Number(explicit[4]),Number(explicit[3])),source:explicit[0]};
  const simple=all.match(/(\d{1,2})\.\s*(\d{1,2})\.?\s*[-–—]\s*(\d{1,2})\.\s*(\d{1,2})\.?\s*(\d{4})/);
  if(simple)return{from:iso(Number(simple[5]),Number(simple[2]),Number(simple[1])),to:iso(Number(simple[5]),Number(simple[4]),Number(simple[3])),source:simple[0]};
  return{from:null,to:null,source:null};
}
async function ensureImport(s:any,args:{bucket:string;path:string;retailer:string;sourceUrl:string|null}){const key=`leaflet-staging:${args.bucket}:${args.path}`;const{data:old,error:oe}=await s.from("imports").select("id").eq("import_batch_key",key).maybeSingle();if(oe)throw new Error(`imports lookup: ${oe.message}`);if(typeof old?.id==="string")return old.id;const{data,error}=await s.from("imports").insert({source_type:"leaflet",source_url:args.sourceUrl,note:`leaflet_staging | retailer:${args.retailer} | storage:${args.bucket}/${args.path}`,import_batch_key:key,import_contract_version:"leaflet-staging-v3",import_contract_snapshot:{retailer:args.retailer,bucket:args.bucket,path:args.path,model:EXTRACTOR_MODEL}}).select("id").single();if(error||typeof data?.id!=="string")throw new Error(error?.message||"Import nebyl vytvořen.");return data.id;}
async function pageWords(doc:any,pageNo:number):Promise<{words:OcrWord[];text:string}>{const page=await doc.getPage(pageNo);const content=await page.getTextContent();const words:OcrWord[]=[];const parts:string[]=[];for(const raw of content.items){if(!("str" in raw)||typeof raw.str!=="string")continue;const text=raw.str.trim();if(!text)continue;const t=Array.isArray(raw.transform)?raw.transform:[1,0,0,1,0,0];words.push({text,x:Number(t[4]??0),y:Number(t[5]??0),w:Math.max(1,Number(raw.width??text.length*5)),h:Math.max(1,Number(raw.height??Math.abs(Number(t[3]??10))))});parts.push(text);}return{words,text:parts.join(" ")};}
async function refreshCounts(s:any,leafletId:string,pageCount:number,processedPages:number,failed=false){const{data,error}=await s.from("leaflet_item_candidates").select("status").eq("leaflet_id",leafletId);if(error)throw new Error(error.message);const rows=data??[];const count=(x:string)=>rows.filter((r:any)=>r.status===x).length;const unreviewed=count("unreviewed")+count("needs_reread"),approved=count("approved"),rejected=count("rejected"),quarantine=count("quarantine");const status=failed?"failed":processedPages<pageCount?"processing":unreviewed+quarantine>0?"ready_for_review":"completed";const patch={page_count:pageCount,processed_pages:processedPages,candidate_count:rows.length,unreviewed_count:unreviewed,approved_count:approved,rejected_count:rejected,quarantine_count:quarantine,processing_status:status,processing_completed_at:processedPages>=pageCount?new Date().toISOString():null,updated_at:new Date().toISOString()};const{error:u}=await s.from("leaflet_documents").update(patch).eq("id",leafletId);if(u)throw new Error(u.message);return{candidate_count:rows.length,unreviewed_count:unreviewed,approved_count:approved,rejected_count:rejected,quarantine_count:quarantine,processing_status:status};}
async function queueNotification(s:any,leaflet:any,counts:any){const subject=`${String(leaflet.retailer_id).toUpperCase()} – nový leták ke kontrole`;const waiting=counts.unreviewed_count+counts.quarantine_count;const body=`Na ${String(leaflet.retailer_id).toUpperCase()} je nový leták. Zpracováno ${leaflet.page_count} stran, nalezeno ${counts.candidate_count} položek, ${waiting} čeká na kontrolu.`;await s.from("leaflet_notification_outbox").upsert({leaflet_id:leaflet.id,subject,body_text:body,status:"pending"},{onConflict:"leaflet_id,channel"});await s.from("leaflet_documents").update({notification_status:"queued"}).eq("id",leaflet.id);return sendLeafletNotification(s,leaflet.id);}
async function clearPageForReread(s:any,leafletId:string,pageNo:number){const{data}=await s.from("leaflet_item_candidates").select("id,status").eq("leaflet_id",leafletId).eq("page_no",pageNo);const removable=(data??[]).filter((r:any)=>!["approved","rejected"].includes(r.status)).map((r:any)=>r.id);if(removable.length){const{error}=await s.from("leaflet_item_candidates").delete().in("id",removable);if(error)throw new Error(`reread cleanup: ${error.message}`);}}

async function loadPdfDocument(bytes:Uint8Array){
 const worker=await import("pdfjs-dist/legacy/build/pdf.worker.mjs");
 (globalThis as typeof globalThis & {pdfjsWorker?:unknown}).pdfjsWorker={WorkerMessageHandler:worker.WorkerMessageHandler};
 const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");
 const task=pdfjs.getDocument({data:bytes.slice()});
 return task.promise;
}

export async function processLeafletPdf(args:{supabase:any;bucket:string;path:string;retailer:string;sourceUrl:string|null;bytes?:Uint8Array;page?:number|null;force?:boolean}){
 const{suppabase,...unused}=({suppabase:null} as any);void unused;const s=args.supabase;let bytes=args.bytes;if(!bytes){const{data,error}=await s.storage.from(args.bucket).download(args.path);if(error||!data)throw new Error(error?.message||"PDF nebylo nalezeno.");bytes=new Uint8Array(await data.arrayBuffer());}
 const doc=await loadPdfDocument(bytes);
 try{
  const importId=await ensureImport(s,{bucket:args.bucket,path:args.path,retailer:args.retailer,sourceUrl:args.sourceUrl});let firstText="";for(let p=1;p<=Math.min(2,doc.numPages);p++)firstText+=(await pageWords(doc,p)).text+" ";const validity=parseValidity(firstText,args.path,args.sourceUrl);const filename=args.path.split("/").pop()||args.path;const internalKey=`${args.retailer}:${createHash("sha1").update(`${args.bucket}/${args.path}`).digest("hex")}`;
  const base={retailer_id:args.retailer,storage_bucket:args.bucket,storage_path:args.path,filename,source_url:args.sourceUrl,source_leaflet_number:null,internal_leaflet_key:internalKey,valid_from:validity.from,valid_to:validity.to,page_count:doc.numPages,processing_status:"processing",import_id:importId,processing_error:null,updated_at:new Date().toISOString()};const{data:leaflet,error:le}=await s.from("leaflet_documents").upsert(base,{onConflict:"storage_bucket,storage_path"}).select("*").single();if(le||!leaflet)throw new Error(le?.message||"Leaflet document nebyl uložen.");
  const pages=args.page?[args.page]:Array.from({length:doc.numPages},(_,i)=>i+1);let processed=0;
  for(const pageNo of pages){if(pageNo<1||pageNo>doc.numPages)throw new Error(`Stránka musí být 1 až ${doc.numPages}.`);if(args.force)await clearPageForReread(s,leaflet.id,pageNo);const page=await pageWords(doc,pageNo);const extracted=extractLeafletCandidates(page.words,{pageNo,validFrom:validity.from,validTo:validity.to});const{data:existing}=await s.from("leaflet_item_candidates").select("candidate_key,status").eq("leaflet_id",leaflet.id).eq("page_no",pageNo);const locked=new Set((existing??[]).filter((x:any)=>["approved","rejected"].includes(x.status)).map((x:any)=>x.candidate_key));for(const c of extracted){if(locked.has(c.candidate_key))continue;const row={leaflet_id:leaflet.id,...c,currency:"CZK",updated_at:new Date().toISOString()};const{data:saved,error:se}=await s.from("leaflet_item_candidates").upsert(row,{onConflict:"leaflet_id,candidate_key"}).select("id").single();if(se)throw new Error(`candidate: ${se.message}`);if(saved?.id)await s.from("leaflet_item_review_audit").insert({candidate_id:saved.id,action:"extracted",next_payload:row,note:"Automatická evidence-first extrakce; nic není automaticky schváleno."});}processed++;}
  const processedPages=args.page?Math.max(Number(leaflet.processed_pages||0),processed):doc.numPages;const counts=await refreshCounts(s,leaflet.id,doc.numPages,processedPages);const current={...leaflet,page_count:doc.numPages,processed_pages:processedPages,...counts,valid_from:validity.from,valid_to:validity.to};let notification:any=null;if(!args.page&&processedPages>=doc.numPages)notification=await queueNotification(s,current,counts);const{data:candidates}=await s.from("leaflet_item_candidates").select("*").eq("leaflet_id",leaflet.id).order("page_no").limit(args.page?500:20);return{leaflet:current,candidates:candidates??[],validity,notification};
 }catch(error){throw error}finally{await doc.destroy()}
}
