import { NextResponse } from "next/server";
import { requireOperatorApi } from "@/lib/auth/guards";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import type { OcrWord } from "@/lib/ocr/types";
import { extractLeafletCandidates } from "@/lib/leaflet-review/extractor";
export const runtime="nodejs"; export const maxDuration=120;
const BUCKET="leaflet-intake", SOURCE_PATH="billa/billa-2026-08-19__a7a0e1fef9b45d3b.pdf";
async function loadPdfDocument(bytes:Uint8Array){const worker=await import("pdfjs-dist/legacy/build/pdf.worker.mjs");(globalThis as typeof globalThis&{pdfjsWorker?:unknown}).pdfjsWorker={WorkerMessageHandler:worker.WorkerMessageHandler};const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");return pdfjs.getDocument({data:bytes.slice()}).promise;}
async function pageWords(doc:any,pageNo:number):Promise<OcrWord[]>{const page=await doc.getPage(pageNo),content=await page.getTextContent(),words:OcrWord[]=[];for(const raw of content.items){if(!("str" in raw)||typeof raw.str!=="string")continue;const text=raw.str.trim();if(!text)continue;const t=Array.isArray(raw.transform)?raw.transform:[1,0,0,1,0,0];words.push({text,x:Number(t[4]??0),y:Number(t[5]??0),w:Math.max(1,Number(raw.width??text.length*5)),h:Math.max(1,Number(raw.height??Math.abs(Number(t[3]??10))))});}return words;}
const eq=(a:unknown,b:number)=>Math.abs(Number(a)-b)<.001;
export async function GET(){const gate=await requireOperatorApi();if(!gate.ok)return gate.response;const s=getSupabaseAdmin();if(!s)return NextResponse.json({ok:false,error:"Supabase není nakonfigurovaný."},{status:503});let doc:any=null;try{const {data:source,error}=await s.storage.from(BUCKET).download(SOURCE_PATH);if(error||!source)throw new Error(error?.message||"BILLA PDF chybí.");doc=await loadPdfDocument(new Uint8Array(await source.arrayBuffer()));const rows=extractLeafletCandidates(await pageWords(doc,1),{pageNo:1,validFrom:"2026-08-19",validTo:"2026-08-25"});const find=(sale:number,rx:RegExp)=>rows.filter(r=>eq(r.price_sale,sale)).find(r=>rx.test(String(r.source_text||"")));const pilsner=find(28.83,/Urquell/i), rajcata=find(39.9,/Rajčata/i), paper=find(99.9,/Toaletní|papír/i), milka=find(24.9,/Milka|Čokoláda/i);const checks=[{id:"pilsner_unit",value:pilsner?{price_per_unit:pilsner.price_per_unit,unit:pilsner.price_per_unit_unit}:null,ok:!!pilsner&&eq(pilsner.price_per_unit,57.67)&&/1\s*l/i.test(String(pilsner.price_per_unit_unit||""))},{id:"rajcata_unit",value:rajcata?{price_per_unit:rajcata.price_per_unit,unit:rajcata.price_per_unit_unit}:null,ok:!!rajcata&&eq(rajcata.price_per_unit,15.96)&&/100\s*g/i.test(String(rajcata.price_per_unit_unit||""))},{id:"paper_unit",value:paper?{price_per_unit:paper.price_per_unit,unit:paper.price_per_unit_unit}:null,ok:!!paper&&eq(paper.price_per_unit,.28)&&/1\s*m/i.test(String(paper.price_per_unit_unit||""))},{id:"milka_promo",value:milka?{minimum_quantity:milka.minimum_quantity,promo_condition:milka.promo_condition}:null,ok:!!milka&&milka.minimum_quantity===1&&/při\s+koupi/i.test(String(milka.promo_condition||""))}];const failures=checks.filter(c=>!c.ok).map(c=>c.id);return NextResponse.json({ok:true,point_5f:{pass:failures.length===0,checks,failures}});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}finally{if(doc)await doc.destroy();}}
