-- Restore the runtime contract shared by setrik.cz and leaflet-review-app.
-- The recovery database is intentionally empty; this migration must remain
-- safe to re-run on a freshly restored project.

begin;

-- setrik.cz addresses retailers by stable text slugs and expects these exact
-- branch column names. Recreate only while there is no recovered branch data.
do $$
begin
  if exists (select 1 from public.store_branches limit 1) then
    raise exception 'store_branches contains data; migrate it explicitly instead of recreating the table';
  end if;
end
$$;

alter table public.offers_raw
  drop constraint if exists offers_raw_store_branch_id_fkey;
drop table if exists public.store_branches;

create table public.store_branches (
  id bigint generated by default as identity primary key,
  retailer_id text not null references public.retailers(slug) on update cascade on delete restrict,
  external_id text null,
  branch_name text not null,
  address_line text not null,
  city text not null,
  postal_code text null,
  region text null,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (retailer_id, external_id)
);

alter table public.offers_raw
  add constraint offers_raw_store_branch_id_fkey
  foreign key (store_branch_id) references public.store_branches(id) on delete set null;

create index if not exists store_branches_city_active_idx
  on public.store_branches (city, is_active);
create index if not exists store_branches_retailer_active_idx
  on public.store_branches (retailer_id, is_active);

alter table public.store_branches enable row level security;
create policy branches_public_read on public.store_branches
  for select to anon, authenticated using (is_active);
revoke all on table public.store_branches from anon, authenticated;
grant select on table public.store_branches to anon, authenticated;
grant all on table public.store_branches to service_role;
grant usage, select on sequence public.store_branches_id_seq to service_role;

-- Append-only price history. The source offer uses BIGINT, while imports use
-- UUID in the recovered production-compatible contract.
create table if not exists public.offer_price_snapshots (
  id bigint generated always as identity primary key,
  created_at timestamptz not null default now(),
  offers_raw_id bigint not null references public.offers_raw(id) on delete cascade,
  import_id uuid null references public.imports(id) on delete set null,
  store_id text not null,
  product_family_key text null,
  comparable_group_key text null,
  price_total numeric not null check (price_total > 0),
  currency text not null default 'CZK',
  snapshot_revision integer not null check (snapshot_revision > 0),
  constraint offer_price_snapshots_offers_raw_id_snapshot_revision_key
    unique (offers_raw_id, snapshot_revision)
);

create index if not exists offer_price_snapshots_import_id_idx
  on public.offer_price_snapshots(import_id) where import_id is not null;
create index if not exists idx_offer_price_snapshots_store_family_created
  on public.offer_price_snapshots(store_id, product_family_key, created_at desc);
create index if not exists idx_offer_price_snapshots_store_comparable_created
  on public.offer_price_snapshots(store_id, comparable_group_key, created_at desc);
create index if not exists idx_offer_price_snapshots_created_at
  on public.offer_price_snapshots(created_at desc);

create sequence if not exists public.offer_price_snapshot_revision_seq
  as integer increment by 1 minvalue 1 start with 1 cache 100;

create schema if not exists private;
create or replace function private.capture_offer_price_snapshot()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
begin
  if new.price_total is null or new.price_total::numeric <= 0 then
    return new;
  end if;
  if tg_op = 'UPDATE' and new.price_total is not distinct from old.price_total then
    return new;
  end if;

  insert into public.offer_price_snapshots (
    offers_raw_id, import_id, store_id, product_family_key,
    comparable_group_key, price_total, currency, snapshot_revision
  ) values (
    new.id, new.import_id, coalesce(new.store_id::text, ''), new.product_family_key,
    new.comparable_group_key, new.price_total::numeric, coalesce(new.currency, 'CZK'),
    nextval('public.offer_price_snapshot_revision_seq')::integer
  );
  return new;
end
$$;

revoke all on function private.capture_offer_price_snapshot() from public, anon, authenticated;
grant execute on function private.capture_offer_price_snapshot() to service_role;

drop trigger if exists offers_raw_after_insert_price_snapshot on public.offers_raw;
drop trigger if exists offers_raw_after_price_total_update_snapshot on public.offers_raw;
create trigger offers_raw_after_insert_price_snapshot
  after insert on public.offers_raw
  for each row execute function private.capture_offer_price_snapshot();
create trigger offers_raw_after_price_total_update_snapshot
  after update of price_total on public.offers_raw
  for each row when (old.price_total is distinct from new.price_total)
  execute function private.capture_offer_price_snapshot();

alter table public.offer_price_snapshots enable row level security;
create policy offer_price_snapshots_select_public on public.offer_price_snapshots
  for select to anon, authenticated using (true);
revoke all on table public.offer_price_snapshots from anon, authenticated;
grant select on table public.offer_price_snapshots to anon, authenticated;
grant all on table public.offer_price_snapshots to service_role;
grant usage, select on sequence public.offer_price_snapshots_id_seq to service_role;
grant usage, select on sequence public.offer_price_snapshot_revision_seq to service_role;

-- Public callers get only current, approved leaflet offers. Access to the
-- operational source tables stays behind the SECURITY DEFINER boundary.
drop view if exists public.leaflet_offers_visible;
create or replace function public.get_active_leaflet_offers()
returns setof public.offers_visible
language sql
stable
security definer
set search_path = public
as $$
  select v
  from public.offers_visible v
  where v.source_type = 'leaflet'
    and exists (
      select 1
      from public.offers_raw o
      join public.leaflet_documents d on d.id = o.leaflet_id
      where o.id = v.id
        and d.retailer_id = v.store_id
        and d.valid_from is not null
        and d.valid_to is not null
        and current_date between d.valid_from and d.valid_to
        and current_date between v.valid_from and v.valid_to
    )
$$;

revoke all on function public.get_active_leaflet_offers() from public;
grant execute on function public.get_active_leaflet_offers() to anon, authenticated;

commit;
