import { NextResponse } from "next/server";
import { requireOperatorApi } from "@/lib/auth/guards";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import { processLeafletPdf } from "@/lib/leaflet-review/processor";
export const runtime="nodejs"; export const maxDuration=180;
const BUCKET="leaflet-intake", SOURCE_PATH="billa/billa-2026-08-19__a7a0e1fef9b45d3b.pdf";
const eq=(a:unknown,b:number)=>Math.abs(Number(a)-b)<.001;
async function cleanup(s:any,leafletId:string|null,importId:string|null){if(!leafletId)return;const{data:c}=await s.from("leaflet_item_candidates").select("id").eq("leaflet_id",leafletId);const ids=(c??[]).map((x:any)=>x.id).filter(Boolean);if(ids.length)await s.from("leaflet_item_review_audit").delete().in("candidate_id",ids);await s.from("leaflet_notification_outbox").delete().eq("leaflet_id",leafletId);await s.from("leaflet_item_candidates").delete().eq("leaflet_id",leafletId);await s.from("leaflet_page_processing").delete().eq("leaflet_id",leafletId);await s.from("leaflet_documents").delete().eq("id",leafletId);if(importId)await s.from("imports").delete().eq("id",importId);}
export async function GET(){const gate=await requireOperatorApi();if(!gate.ok)return gate.response;const s=getSupabaseAdmin();if(!s)return NextResponse.json({ok:false,error:"Supabase není nakonfigurovaný."},{status:503});const testPath=`_tests/billa-19-08-2026-25-08-2026-complete-${Date.now()}.pdf`;let leafletId:string|null=null,importId:string|null=null;try{const{data:source,error}=await s.storage.from(BUCKET).download(SOURCE_PATH);if(error||!source)throw new Error(error?.message||"BILLA PDF chybí.");const bytes=new Uint8Array(await source.arrayBuffer());await processLeafletPdf({supabase:s,bucket:BUCKET,path:testPath,retailer:"billa",sourceUrl:"test://complete-card/billa",bytes,page:1,force:true});const{data:doc,error:de}=await s.from("leaflet_documents").select("id,import_id,valid_from,valid_to").eq("storage_bucket",BUCKET).eq("storage_path",testPath).single();if(de||!doc?.id)throw new Error(de?.message||"Testovací dokument nevznikl.");leafletId=String(doc.id);importId=typeof doc.import_id==="string"?doc.import_id:null;const{data:rows,error:re}=await s.from("leaflet_item_candidates").select("product_name,brand,variant,pack_qty,pack_unit,pack_unit_qty,pack_text,price_sale,price_standard,price_loyalty,price_without_loyalty,price_per_unit,price_per_unit_unit,minimum_quantity,promo_condition,leaflet_valid_from,leaflet_valid_to,field_evidence,source_text").eq("leaflet_id",leafletId).eq("page_no",1);if(re)throw new Error(re.message);const at=(price:number,rx:RegExp)=>(rows??[]).find((x:any)=>eq(x.price_sale,price)&&rx.test(String(x.source_text||"")));const milka=at(24.9,/Milka|Čokoláda/i),hrozny=at(39.9,/Hrozny/i),paper=at(99.9,/Toaletní|papír/i),maslo=at(32.9,/Jihočeské\s+máslo/i);const checks=[
{id:"validity",value:{from:doc.valid_from,to:doc.valid_to},ok:doc.valid_from==="2026-08-19"&&doc.valid_to==="2026-08-25"},
{id:"milka_complete",value:milka??null,ok:!!milka&&/Čokoláda/i.test(String(milka.product_name||""))&&milka.brand==="Milka"&&milka.variant==null&&eq(milka.pack_qty,1)&&eq(milka.pack_unit_qty,90)&&milka.pack_unit==="g"&&eq(milka.price_sale,24.9)&&milka.minimum_quantity===2&&/^OD\s+2\s+KS$/i.test(String(milka.promo_condition||""))},
{id:"hrozny_complete",value:hrozny??null,ok:!!hrozny&&/Hrozny/i.test(String(hrozny.product_name||""))&&hrozny.variant==="vinné bílé"&&eq(hrozny.pack_qty,1)&&eq(hrozny.pack_unit_qty,1)&&hrozny.pack_unit==="kg"&&eq(hrozny.price_sale,39.9)&&eq(hrozny.price_standard,84.9)},
{id:"paper_complete",value:paper??null,ok:!!paper&&paper.brand==="Linteo"&&eq(paper.pack_qty,1)&&eq(paper.pack_unit_qty,360)&&paper.pack_unit==="m"&&eq(paper.price_sale,99.9)&&eq(paper.price_standard,139.9)&&eq(paper.price_per_unit,.28)&&/1\s*m/i.test(String(paper.price_per_unit_unit||""))},
{id:"maslo_prices",value:maslo??null,ok:!!maslo&&eq(maslo.pack_unit_qty,250)&&maslo.pack_unit==="g"&&eq(maslo.price_sale,32.9)&&eq(maslo.price_standard,44.9)&&eq(maslo.price_loyalty,32.9)&&eq(maslo.price_without_loyalty,44.9)},
{id:"field_evidence",value:{brand:milka?.field_evidence?.brand?.source??null,variant:hrozny?.field_evidence?.variant?.source??null,promo:milka?.field_evidence?.promo_condition?.source??null},ok:milka?.field_evidence?.brand?.source==="brand_aliases"&&hrozny?.field_evidence?.variant?.source==="product_block_text"&&milka?.field_evidence?.promo_condition?.source==="nearby_product_block_text"}
];const failures=checks.filter(x=>!x.ok).map(x=>x.id);return NextResponse.json({ok:failures.length===0,point_5g:{pass:failures.length===0,checks,failures}});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}finally{try{await cleanup(s,leafletId,importId);}catch(error){console.error("test-complete-card cleanup failed",error);}}}
